import { PropsWithChildren } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, TextInputProps, View } from 'react-native';

export function Title({ children }: PropsWithChildren) { return <Text style={styles.title}>{children}</Text>; }
export function Card({ children }: PropsWithChildren) { return <View style={styles.card}>{children}</View>; }
export function Field(props: TextInputProps & { label: string }) { return <View style={styles.field}><Text style={styles.label}>{props.label}</Text><TextInput {...props} style={styles.input} placeholderTextColor="#9c978f" /></View>; }
export function Button({ title, onPress, disabled, secondary = false, loading = false }: { title: string; onPress: () => void; disabled?: boolean; secondary?: boolean; loading?: boolean }) {
  return <Pressable accessibilityRole="button" disabled={disabled || loading} onPress={onPress} style={({ pressed }) => [styles.button, secondary && styles.secondary, (pressed || disabled) && styles.dim]}>{loading ? <ActivityIndicator color={secondary ? '#ff4f5e' : '#fff'} /> : <Text style={[styles.buttonText, secondary && styles.secondaryText]}>{title}</Text>}</Pressable>;
}
export const ui = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#f7f4ef' }, content: { padding: 20, gap: 16 }, eyebrow: { color: '#ff4f5e', fontWeight: '800', letterSpacing: 1.2, textTransform: 'uppercase', marginBottom: 6 }, muted: { color: '#6d6963', fontSize: 15, lineHeight: 21 }, error: { color: '#a82532', backgroundColor: '#ffe8ea', padding: 12, borderRadius: 12, overflow: 'hidden' }, success: { color: '#246b44', backgroundColor: '#e7f7ee', padding: 12, borderRadius: 12, overflow: 'hidden' }, row: { flexDirection: 'row', gap: 10, alignItems: 'center' } });
const styles = StyleSheet.create({ title: { fontSize: 32, fontWeight: '800', color: '#20201f', letterSpacing: -0.8 }, card: { backgroundColor: '#fff', borderRadius: 20, padding: 18, gap: 14, shadowColor: '#28231e', shadowOpacity: 0.08, shadowRadius: 14, shadowOffset: { width: 0, height: 5 } }, field: { gap: 6 }, label: { fontSize: 13, fontWeight: '700', color: '#55514c' }, input: { backgroundColor: '#f7f4ef', borderWidth: 1, borderColor: '#e7e1d8', borderRadius: 12, padding: 13, fontSize: 16, color: '#20201f' }, button: { minHeight: 50, borderRadius: 14, backgroundColor: '#ff4f5e', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 16 }, secondary: { backgroundColor: '#fff0f1', borderWidth: 1, borderColor: '#ffcbd0' }, dim: { opacity: 0.55 }, buttonText: { color: '#fff', fontWeight: '800', fontSize: 16 }, secondaryText: { color: '#d53243' } });
