import { PropsWithChildren, ReactNode } from 'react';
import { ActivityIndicator, DynamicColorIOS, Platform, PlatformColor, Pressable, StyleSheet, Text, TextInput, TextInputProps, View } from 'react-native';

const adaptive = (light: string, dark: string) => Platform.OS === 'ios' ? DynamicColorIOS({ light, dark }) : light;
const system = (iosName: string, fallback: string) => Platform.OS === 'ios' ? PlatformColor(iosName) : fallback;

export const colors = {
  tint: system('systemBlueColor', '#007AFF'), destructive: system('systemRedColor', '#FF3B30'), label: system('labelColor', '#000000'), secondaryLabel: system('secondaryLabelColor', '#6C6C70'), tertiaryLabel: system('tertiaryLabelColor', '#8E8E93'), separator: system('separatorColor', '#C6C6C8'), systemBackground: system('systemBackgroundColor', '#FFFFFF'), secondarySystemBackground: system('secondarySystemBackgroundColor', '#F2F2F7'), systemGroupedBackground: system('systemGroupedBackgroundColor', '#F2F2F7'), secondaryGroupedBackground: system('secondarySystemGroupedBackgroundColor', '#FFFFFF'), bar: adaptive('rgba(249,249,249,0.96)', 'rgba(29,29,31,0.96)'), errorBackground: adaptive('#FFE8E7', '#4A1917'), successBackground: adaptive('#E7F7EC', '#133822'), success: adaptive('#247A3E', '#5DD27D'),
};

export function LargeTitle({ children }: PropsWithChildren) { return <Text accessibilityRole="header" style={styles.largeTitle}>{children}</Text>; }
export function Section({ title, footer, children }: PropsWithChildren<{ title?: string; footer?: string }>) { return <View style={styles.section}>{title ? <Text style={styles.sectionTitle}>{title}</Text> : null}<View style={styles.group}>{children}</View>{footer ? <Text style={styles.footer}>{footer}</Text> : null}</View>; }
export function Separator() { return <View style={styles.separator} />; }
export function Field({ label, ...props }: TextInputProps & { label: string }) { return <View style={styles.fieldRow}><Text style={styles.fieldLabel}>{label}</Text><TextInput {...props} style={styles.input} placeholderTextColor={colors.tertiaryLabel} selectionColor={colors.tint} /></View>; }
export function ActionButton({ title, onPress, disabled, destructive = false, loading = false }: { title: string; onPress: () => void; disabled?: boolean; destructive?: boolean; loading?: boolean }) { const color = destructive ? colors.destructive : colors.tint; return <Pressable accessibilityRole="button" disabled={disabled || loading} onPress={onPress} style={({ pressed }) => [styles.action, (pressed || disabled) && styles.dim]}>{loading ? <ActivityIndicator color={color} /> : <Text style={[styles.actionText, { color }]}>{title}</Text>}</Pressable>; }
export function ListRow({ title, detail, selected, onPress, trailing }: { title: string; detail?: string; selected?: boolean; onPress?: () => void; trailing?: ReactNode }) { const content = <><View style={styles.rowText}><Text style={styles.rowTitle}>{title}</Text>{detail ? <Text style={styles.rowDetail}>{detail}</Text> : null}</View>{trailing ?? (selected ? <Text style={styles.check}>✓</Text> : onPress ? <Text style={styles.chevron}>›</Text> : null)}</>; return onPress ? <Pressable accessibilityRole="button" onPress={onPress} style={({ pressed }) => [styles.listRow, pressed && styles.pressed]}>{content}</Pressable> : <View style={styles.listRow}>{content}</View>; }
export function Notice({ children, kind = 'error' }: PropsWithChildren<{ kind?: 'error' | 'success' }>) { return <Text style={[styles.notice, kind === 'success' ? styles.success : styles.error]}>{children}</Text>; }

export const ui = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.systemGroupedBackground }, safe: { flex: 1, backgroundColor: colors.systemGroupedBackground }, content: { paddingHorizontal: 16, paddingBottom: 28, gap: 18 }, header: { paddingHorizontal: 20, paddingTop: 10, paddingBottom: 8 }, muted: { color: colors.secondaryLabel, fontSize: 15, lineHeight: 20 } });
const styles = StyleSheet.create({ largeTitle: { color: colors.label, fontSize: 34, lineHeight: 41, fontWeight: '700', letterSpacing: 0.3 }, section: { gap: 7 }, sectionTitle: { color: colors.secondaryLabel, fontSize: 13, lineHeight: 18, textTransform: 'uppercase', marginLeft: 16 }, group: { backgroundColor: colors.secondaryGroupedBackground, borderRadius: 10, overflow: 'hidden' }, footer: { color: colors.secondaryLabel, fontSize: 13, lineHeight: 18, marginHorizontal: 16 }, separator: { height: StyleSheet.hairlineWidth, backgroundColor: colors.separator, marginLeft: 16 }, fieldRow: { minHeight: 50, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, gap: 12 }, fieldLabel: { color: colors.label, fontSize: 17, width: 82 }, input: { flex: 1, color: colors.label, fontSize: 17, paddingVertical: 11, textAlign: 'right' }, action: { minHeight: 50, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 16 }, actionText: { fontSize: 17, fontWeight: '400' }, dim: { opacity: 0.42 }, listRow: { minHeight: 50, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, gap: 10 }, pressed: { backgroundColor: colors.secondarySystemBackground }, rowText: { flex: 1, paddingVertical: 9 }, rowTitle: { color: colors.label, fontSize: 17, lineHeight: 22 }, rowDetail: { color: colors.secondaryLabel, fontSize: 13, lineHeight: 17, marginTop: 1 }, check: { color: colors.tint, fontSize: 20, fontWeight: '600' }, chevron: { color: colors.tertiaryLabel, fontSize: 28, lineHeight: 28, fontWeight: '300' }, notice: { fontSize: 15, lineHeight: 20, paddingHorizontal: 14, paddingVertical: 11, borderRadius: 10, overflow: 'hidden' }, error: { color: colors.destructive, backgroundColor: colors.errorBackground }, success: { color: colors.success, backgroundColor: colors.successBackground } });
